cache = true
cache_exclude_status = "400.."
max_cache_age = "7d"

exclude = [
    # Looks like cppreference.com now hates automatic link checking
    "en.cppreference.com/w/c/chrono/timespec_get.html",
    # ...and Doxygen hates it too, but that's mutual I hate Doxygen as well
    "www.doxygen.org/index.html",
]
exclude_path = [
    # Flaky links in fonts license READMEs are not considered harmful
    ".*fonts/SOURCE-CODE-PRO-LICENSE.txt",
    # Ignore some brokenness outside our control in doxygen's CSS
    "doxygen/doxygen.css",
]

timeout = 5
