# The AlmaLinux image only contains the bare minimum needed to build Udipe. It
# is used to check those minimal build requirements and to make sure that Udipe
# remains compatible with the software versions featured in Alma.

FROM docker.io/almalinux:10

RUN dnf install --nodocs --setopt=install_weak_deps=False -y  \
                cmake gcc glibc-devel hwloc-devel make pkgconf tar  \
    && dnf clean all
