#pragma once

//! \file
//! \brief Message logger
//!
//! This code module implements the logging facility used by udipe to report
//! various events throughout the library execution lifecycle.

#include <udipe/log.h>
#include <udipe/nodiscard.h>
#include <udipe/pointer.h>

#include "scope.h"

#include <assert.h>
#include <stdbool.h>
#include <threads.h>


/// \name Logger set up
/// \{

/// Message logger
///
/// This struct is created by logger_initialize() and contains all information
/// needed to perform logging using the primitives from `src/log.h`.
///
/// For now, this is just a typedef of \ref udipe_log_config_t which encodes the
/// extra invariant that all zero placeholders have been replaced with
/// corresponding default values.
typedef udipe_log_config_t logger_t;

/// Initialize a logger
///
/// This should be done as early as possible during the `libudipe`
/// initialization process in order to minimize the amount of code that cannot
/// perform logging.
///
/// \param config should be valid per \link #udipe_log_config_t the type
///        definition. \endlink
///
/// \return A logger that can be passed to LOGGER_START() as long as the
///         surrounding \ref udipe_context_t has not been finalized.
UDIPE_NODISCARD
logger_t logger_initialize(udipe_log_config_t config);

/// Finalize a logger
///
/// The logger cannot be used again after this is done.
///
/// This should be done as late as possible during the `libudipe` finalization
/// process in order to minimize the amount of code that cannot perform logging.
///
/// \param logger should be a logger that has been set up via
///               logger_initialize() and hasn't been finalized yet.
UDIPE_NON_NULL_ARGS
void logger_finalize(logger_t* logger);

///@}


/// \name Basic logging
/// \{

/// Decide if a user log should be emitted
///
/// This function can only be called within a logging scope.
///
/// This function is implicitly called by the logging macros, but you may want
/// to use it manually in situations where the logging message is not a static
/// string but a string that is dynamically generated by something like
/// sprintf().
///
/// Doing so ensures that the associated dynamic string processing will not be
/// performed when the specified log level is disabled. Otherwise you are at the
/// mercy of compiler optimizations for this, which are notoriously unreliable
/// in the presence of memory allocation and system calls.
UDIPE_NODISCARD
static inline bool log_enabled(udipe_log_level_t level);

/// Log a message if `level` is above configured logging threshold
///
/// This macro can only be used within a logging scope. It takes as input a
/// \link #udipe_log_level_t log level \endlink and the message to be logged at
/// this log level (as a standard `NULL`-terminated `const char[]`).
///
/// You should prefer using the log level specific macros error(), warn(),
/// info(), debug() and trace() over this one, outside of special circumstances
/// where you want to dynamically adjust the log level at runtime.
///
/// If generating a message requires expensive processing that should not be
/// performed when the target log level is disabled, then you should use
/// log_enabled() to test ahead of time whether this log level is enabled. For
/// the common case where the expensive process is generation of a formatted
/// text, we directly provide udipe_logf() and log level specific cousins
/// thereof.
///
/// See also warn_on_errno() for cases where you need to report a failure from
/// system calls and third-party C libraries.
#define udipe_log(level, message)  \
    do {  \
        const udipe_log_level_t udipe_level = thread_log_level(level);  \
        if (log_enabled(udipe_level)) {  \
            (udipe_thread_logger->callback)(udipe_thread_logger->context,  \
                                            udipe_level,  \
                                            __func__,  \
                                            (message));  \
        }  \
    } while(false)

/// Log a \link #UDIPE_TRACE `TRACE` \endlink message
///
/// Must be called within a logging scope. See udipe_log() for more info.
#define trace(message)  udipe_log(UDIPE_TRACE, (message))

/// Log a \link #UDIPE_DEBUG `DEBUG` \endlink message
///
/// Must be called within a logging scope. See udipe_log() for more info.
#define debug(message)  udipe_log(UDIPE_DEBUG, (message))

/// Log an \link #UDIPE_INFO `INFO` \endlink message
///
/// Must be called within a logging scope. See udipe_log() for more info.
#define info(message)  udipe_log(UDIPE_INFO, (message))

/// Log a \link #UDIPE_WARN `WARN` \endlink message
///
/// Must be called within a logging scope. See udipe_log() for more info.
#define warn(message)  udipe_log(UDIPE_WARN, (message))

/// Log an \link #UDIPE_ERROR `ERROR` \endlink message
///
/// Must be called within a logging scope. See udipe_log() for more info.
#define error(message)  udipe_log(UDIPE_ERROR, (message))

/// \}


/// \name Formatted logging
/// \{

/// Log a message with printf() formatting
///
/// This macro works a lot like udipe_log(), but instead of logging a
/// pre-existing string, it builds a string on the fly using a printf()-style
/// format string and formatting arguments.
///
/// The price to pay for these enhanced formating capabilities is extra runtime
/// overhead, so prefer the basic logging macros where all you need to log is a
/// static string.
///
/// All other comments from udipe_log() remain valid, including the need to call
/// it within a logging scope. See also errorf(), warnf(), infof(), debugf() and
/// tracef() for level-specific formatted logging macros.
#define udipe_logf(level, format, ...)  \
    do {  \
        const udipe_log_level_t udipe_level = thread_log_level(level);  \
        if (log_enabled(udipe_level)) {  \
            logf_impl(udipe_level,  \
                      __func__,  \
                      (format),  \
                      __VA_ARGS__);  \
        }  \
    } while(false)

/// Log a \link #UDIPE_TRACE `TRACE` \endlink formatted message
///
/// Must be called within a logging scope. See udipe_logf() for more info.
#define tracef(format, ...)  udipe_logf(UDIPE_TRACE, (format), __VA_ARGS__)

/// Log a \link #UDIPE_DEBUG `DEBUG` \endlink formatted message
///
/// Must be called within a logging scope. See udipe_logf() for more info.
#define debugf(format, ...)  udipe_logf(UDIPE_DEBUG, (format), __VA_ARGS__)

/// Log an \link #UDIPE_INFO `INFO` \endlink formatted message
///
/// Must be called within a logging scope. See udipe_logf() for more info.
#define infof(format, ...)  udipe_logf(UDIPE_INFO, (format), __VA_ARGS__)

/// Log a \link #UDIPE_WARN `WARN` \endlink formatted message
///
/// Must be called within a logging scope. See udipe_logf() for more info.
#define warnf(format, ...)  udipe_logf(UDIPE_WARN, (format), __VA_ARGS__)

/// Log an \link #UDIPE_ERROR `ERROR` \endlink formatted message
///
/// Must be called within a logging scope. See udipe_logf() for more info.
#define errorf(format, ...)  udipe_logf(UDIPE_ERROR, (format), __VA_ARGS__)

/// \}


/// \name Expression logging
/// \{

/// Log an expression and its value at \link #UDIPE_DEBUG `DEBUG` \endlink
/// level, along with the associated code location.
///
/// This macro is only meant for debugging purpose and should not appear
/// anywhere in production code.
///
/// It must be called within a logging scope.
///
/// \internal
///
/// If you are trying to understand the implementation of this macro, then you
/// need to know that in order to produce an appropriate format string for
/// operand `expr`, which may be of nearly any type, there is quite a lot to do:
///
/// - First we use format_for() to determine an appropriate format specifier for
///   input expressions `expr`.
/// - Then we generate a format string that uses these format specifiers.
///   * This is needed because the output of format_for() cannot be concatenated
///     with the rest of the format string at compile time.
///   * It means that arguments other than the format specifiers must be escaped
///     with a double percent sign so that they are not used during this first
///     formatting pass, but become valid format specifiers afterwards.
/// - Generate an error message based on this format string.
///   * This step is needed because the debugf() macro does not have a
///     `vdebugf()` variant that takes a `va_list`.
/// - Log this error message at debug() level.
#define debug_expr(expr)  \
    do {  \
        if (log_enabled(UDIPE_DEBUG)) {  \
            debug_expr_impl("At %%s:%%u.\n"  \
                            "Evaluated %%s\n"  \
                            "       => %s",   \
                            format_for(expr),  \
                            __FILE__, __LINE__, #expr, expr);  \
        }  \
    } while(false)

/// \}


/// \name Thread-local logger
/// \{

/// Start a scope where a certain logger is enabled
///
/// This macro must be used together with \ref LOGGER_END in the same fashion as
/// \ref SCOPE_START and \ref SCOPE_END. Indeed, it is based on the same
/// udipe-tracked scope infrastructure and starts a scope along the way.
///
/// A logging scope must be started at the start of every public `libudipe` API
/// entry point, and early on inside the main function of every worker thread.
/// That is a prerequisite before logging macros (like udipe_log(), info()...)
/// and functions that make logging calls can be used. See also \ref
/// LOGGED_FUNCTION_START.
///
/// \param logger_ptr must point to a `logger_t` that was previously initialized
///        by logger_initialize(), hasn't been finalized yet and that is valid
///        to use until the LOGGER_END scope-ending macro.
#define LOGGER_START(logger_ptr)  \
    do {  \
        logger_t* const udipe_prev_logger = udipe_thread_logger;  \
        udipe_thread_logger = (logger_ptr);  \
        debugf("Set up logger %p.", logger_ptr);  \
        SCOPE_START_WITH_DESTRUCTOR(restore_thread_logger,  \
                                    (void*)udipe_prev_logger)

/// End a scope where a certain logger is enabled
///
/// This macro must be used with \ref LOGGER_START in the same fashion as \ref
/// SCOPE_START pairs with \ref SCOPE_END. It marks the point where the
/// previously enabled logger will be disabled and the former logger (if any)
/// will be restored. No logging should be performed after this point.
///
/// See \ref LOGGER_START for more information about how logging scopes work and
/// where they should be used.
#define LOGGER_END  \
        SCOPE_END  \
    } while(false);

/// Start the logging scope of a certain function
///
/// In addition to setting up a logger with \ref LOGGER_START at the entrance of
/// each public API entry point and at the start of every worker thread, the
/// udipe logging infrastructure demands that every other function that performs
/// logging also starts with this macro and ends with \ref LOGGED_FUNCTION_END.
///
/// This admittedly unpleasant pattern enables the following :
///
/// - Consistently logging function arguments at the \ref UDIPE_DEBUG log level,
///   enabling function call tracing with a consistent syntax during debugging.
/// - Tracking the depth of call stacks via the udipe scope tracking
///   infrastructure, enabling logs to be filtered by call stack depth. This
///   form of log filtering is often needed when displaying logs at the \ref
///   UDIPE_DEBUG level, as those can be too verbose otherwise resulting in
///   excessive slowdown and useful information being drown in noise.
///
/// \param args_format must be a printf format string indicating how the
///                    arguments of the function should be displayed. For
///                    example, for a function that takes a size_t argument and
///                    a string argument, this could be "%zu, %s". Remaining
///                    arguments provide the arguments in the specified order.
///                    The special case of functions that take no parameters can
///                    be handled via the dedicated macro \ref
///                    LOGGED_FUNCTION_START_NO_PARAMS.
#define LOGGED_FUNCTION_START(args_format, ...)  \
    do {  \
        SCOPE_START_WITH_DESTRUCTOR(debug_function_return, (void*)__func__)  \
            debugf("Called function %s(" args_format ")",  \
                   __func__,  \
                   __VA_ARGS__);

/// Variant of \ref LOGGED_FUNCTION_START for functions that take no parameters
///
/// This macro only exists to work around a stupid limitation of the C
/// preprocessor, see \ref LOGGED_FUNCTION_START for general semantics.
#define LOGGED_FUNCTION_START_NO_PARAMS  LOGGED_FUNCTION_START("%s", "")

/// End the logging scope of a certain function
///
/// This macro must be used at the end of every function that starts with \ref
/// LOGGED_FUNCTION_START, it marks the end of the region where logging is
/// allowed.
#define LOGGED_FUNCTION_END  \
        SCOPE_END  \
    } while(false);

/// Set up the thread-local relative log level
///
/// Call as `with_log_level(level, { ... })` to adjust how the \link #UDIPE_INFO
/// `INFO`\endlink and \link #UDIPE_DEBUG `DEBUG`\endlink log levels are
/// interpreted inside of the `{ ... }` inner code scope.
///
/// - If this is set to `DEBUG`, then the `INFO` log level is treated as
///   `DEBUG` and the `DEBUG` log level is treated as `TRACE`.
/// - If this is set to `TRACE`, then the `INFO` and `DEBUG` log levels are
///   treated as `TRACE`.
///
/// Setting the relative log level to any other value is forbidden, and this
/// functionality has no effect on the `ERROR`, `WARN` and `TRACE` log levels.
///
/// This functionality is needed in situations where a particular function is
/// called at several different layers of abstraction, and what qualifies as
/// `INFO` logging in one situation qualities as `DEBUG` or `TRACE` logging in
/// another situation. This most frequently comes up in unit tests.
///
/// \param level must be set to \ref UDIPE_DEBUG or \ref UDIPE_TRACE.
#ifdef __GNUC__
    #define with_log_level(level, ...)  \
        do {  \
            const udipe_log_level_t udipe_prev_log_level  \
                __attribute__((__cleanup__(restore_thread_log_level)))  \
                    = udipe_thread_log_level;  \
            udipe_thread_log_level = (level);  \
            assert(udipe_thread_log_level == UDIPE_DEBUG  \
                   || udipe_thread_log_level == UDIPE_TRACE);  \
            debug("Start of a with_log_level() scope.");  \
            do __VA_ARGS__ while(false);  \
        } while(false)
#elif defined(_MSC_VER)
    #define with_log_level(level, ...)  \
        do {  \
            const udipe_log_level_t udipe_prev_log_level  \
                = udipe_thread_log_level;  \
            __try {  \
                udipe_thread_log_level = (level);  \
                assert(udipe_thread_log_level == UDIPE_DEBUG  \
                       || udipe_thread_log_level == UDIPE_TRACE);  \
                debug("Start of a with_log_level() scope.");  \
                do __VA_ARGS__ while(false);  \
            }  \
            __finally {  \
                restore_thread_log_level(&udipe_prev_log_level);  \
            }  \
        } while(false)
#else
    #error "Sorry, we don't support your compiler yet. Please file a bug report about it!"
#endif

/// Thread-local logger state backup
///
/// This struct can be saved from the current thread-local state via
/// logger_backup() and restored into the current thread-local state via
/// logger_restore(). This is typically done in unit tests when spawning test
/// threads that should use the same logger configuration as the main thread.
typedef struct logger_state_s {
    logger_t* logger;  ///< Backup of \ref udipe_thread_logger
    udipe_log_level_t log_level;  ///< Backup of \ref udipe_thread_log_level
} logger_state_t;

/// Save the current thread-local logger state
///
/// This is typically used to propagate the current logger configuration to
/// child threads with logger_restore().
///
/// Bear in mind that the resulting \ref logger_state_t may only be used as long
/// as the underlying \ref logger_t is valid. The simplest way to enforce this
/// is to join the child threads to which the logger configuration has been
/// propagated before the end of the main thread's LOGGER_START/LOGGER_END
/// block.
///
/// \returns a backup of the thread-local logger state
UDIPE_NODISCARD
logger_state_t logger_backup();

/// Restore the thread-local logger state from a backup
///
/// This is typically used to propagate the logger configuration of a main
/// thread, which has been saved with logger_backup(), into a child thread.
///
/// Bear in mind that the resulting state may only be used as long as the
/// underlying logger object is valid. The simplest way to enforce this
/// is to join the child threads to which the logger configuration has been
/// propagated before the end of the main thread's LOGGER_START/LOGGER_END
/// block.
///
/// \param state is a previously saved backup of the thread-local logger state
void logger_restore(const logger_state_t* state);

///@}


/// \name Implementation details
/// @{

/// Internal helper to validate logging call correctness in `Debug` builds
///
/// Does nothing in `Release` builds.
#ifndef NDEBUG
    void validate_log(udipe_log_level_t level);
#else
    static inline void validate_log(udipe_log_level_t) {
        // Intentionally left empty in `Release` builds.
    }
#endif

/// GNU attributes of logf_impl()
///
/// This allows GCC to validate correct usage of this printf()-style function.
/// Extracting it into a macro deduplicates definition/declaration and works
/// around a bug in the doxygen parser.
#ifdef __GNUC__
    #define LOGF_IMPL_ATTRIBUTES __attribute__((format(printf, 3, 4)))  \
                                 UDIPE_NON_NULL_SPECIFIC_ARGS(2, 3)
#else
    #define LOGF_IMPL_ATTRIBUTES
#endif

/// Implementation of udipe_logf()
///
/// This function is not meant to be used directly, it is an implementation
/// detail of the udipe_logf() macro.
LOGF_IMPL_ATTRIBUTES
void logf_impl(udipe_log_level_t level,
               const char* location,
               const char* format,
               ...);

/// Thread-local log level
///
/// This thread-local variable is used by with_log_level() in order to locally
/// override the log level of some logging statements.
extern thread_local udipe_log_level_t udipe_thread_log_level;

/// Thread-local logger (implementation detail of LOGGER_START)
///
/// This thread-local variable is used by LOGGER_START in order to locally
/// enable a lightweight log syntax without explicit logger passing.
extern thread_local logger_t* udipe_thread_logger;

/// Reinterprete the specified log level according to surrounding
/// with_log_level() scopes
UDIPE_NODISCARD
static inline udipe_log_level_t thread_log_level(udipe_log_level_t level) {
    // WARNING: This function is called by the logger implementation and must
    //          therefore not perform any logging. Normal events and non-fatal
    //          errors should not be signaled at all, fatal errors should be
    //          signalled on stderr before exiting.

    validate_log(level);
    switch (level) {
    case UDIPE_DEBUG:
        return (udipe_thread_log_level == UDIPE_TRACE) ? UDIPE_TRACE : UDIPE_DEBUG;
    case UDIPE_INFO:
        switch (udipe_thread_log_level) {
        case UDIPE_TRACE:
            return UDIPE_TRACE;
        case UDIPE_DEBUG:
            return UDIPE_DEBUG;
        default:
            return UDIPE_INFO;
        }
    default:
        return level;
    }
}

/// Restore `udipe_log_level` (implementation detail of with_log_level())
///
/// This helper function enables with_log_level() to clean up after itself
/// through the GNU `__cleanup__` attribute.
static inline void restore_thread_log_level(const udipe_log_level_t* prev_log_level) {
    debug("End of a with_log_level() scope.");
    udipe_thread_log_level = *prev_log_level;
}

/// Record return from a logged function
///
/// This helper function lets LOGGED_FUNCTION_START/LOGGED_FUNCTION_END debug
/// when a logged function is exited, much like it already debugs when a logged
/// function is entered.
///
/// \param context must be a pointer to the function's `__func__`, casted to
///                `void*` for interface compatibility with \ref
///                SCOPE_START_WITH_DESTRUCTOR.
static inline void debug_function_return(void* context) {
    const char* const func = (const char*)context;
    debugf("Returning from %s()", func);
}

/// Restore `udipe_thread_logger`
///
/// This helper function lets LOGGER_START/LOGGER_END restore the former logger.
///
/// \param context must be a pointer to the former \ref logger_t, casted to
///                `void*` for interface compatibility with \ref
///                SCOPE_START_WITH_DESTRUCTOR.
static inline void restore_thread_logger(void* context) {
    debugf("Disabled logger %p, back to %p.",
           udipe_thread_logger,
           context);
    udipe_thread_logger = (logger_t*)context;
}

/// Implementation of debug_expr()
///
/// This is an implementation detail of debug_expr() that you should not call
/// directly.
///
/// See the internal section of the debug_expr() documentation for more
/// information about what it does.
UDIPE_NON_NULL_SPECIFIC_ARGS(1, 2)
void debug_expr_impl(const char* format_template,
                     const char* expr_format,
                     ...);

/// @}


// Implementation of log_enabled (see docs above)
UDIPE_NODISCARD
static inline bool log_enabled(udipe_log_level_t level) {
    // WARNING: This function is called by the logger implementation and must
    //          therefore not perform any logging. Normal events and non-fatal
    //          errors should not be signaled at all, fatal errors should be
    //          signalled on stderr before exiting.

    validate_log(level);
    return level >= udipe_thread_logger->min_level;
}
