# Random line noise required to allow downstream CMake users to use this code.
#
# Proudly stolen from
# https://cliutils.gitlab.io/modern-cmake/chapters/install/installing.html
#
# Don't ask me why it takes so much boilerplate just to do such a basic thing.

# Generate version file, this is needed for versioned find_package() downstream
include(CMakePackageConfigHelpers)
write_basic_package_version_file(UdipeConfigVersion.cmake
                                 VERSION ${PACKAGE_VERSION}
                                 COMPATIBILITY AnyNewerVersion)

# Generate targets file
#
# Could theoretically dump this to UdipeConfig.cmake directly, but then I
# couldn't depend on any library via find_package(), so need this indirection in
# practice for any nontrivial project.
#
install(EXPORT UdipeTargets
        FILE UdipeTargets.cmake
        NAMESPACE Udipe::
        DESTINATION ${CMAKE_INSTALL_LIBDIR}/cmake/Udipe)

# Generate config file based on the autogenerated targets file
configure_file(cmake/UdipeConfig.cmake.in UdipeConfig.cmake @ONLY)
install(FILES "${CMAKE_CURRENT_BINARY_DIR}/UdipeConfig.cmake"
              "${CMAKE_CURRENT_BINARY_DIR}/UdipeConfigVersion.cmake"
              DESTINATION ${CMAKE_INSTALL_LIBDIR}/cmake/Udipe)